In [1]:
import numpy as np

In [2]:
h=np.array([(6,7,8),(9,5,4)])
print(h)

[[6 7 8]
 [9 5 4]]


In [3]:
print(h.ndim)

2


In [4]:
print(h.dtype)

int32


In [5]:
print(h.shape)

(2, 3)


In [6]:
print(h.size)

6


In [11]:
print(h.reshape(3,2))

[[6 7]
 [8 9]
 [5 4]]


In [13]:
print(h.sum())

39


In [14]:
print(np.sqrt(h))

[[2.44948974 2.64575131 2.82842712]
 [3.         2.23606798 2.        ]]


In [15]:
t=np.array([(11,22,33),(44,55,66)])
y=np.array([(89,78,67),(22,33,45)])
print(t+y)

[[100 100 100]
 [ 66  88 111]]


In [16]:
t=np.array([(11,22,33),(44,55,66)])
y=np.array([(89,78,67),(22,33,45)])
print(t-y)

[[-78 -56 -34]
 [ 22  22  21]]


In [17]:
t=np.array([(11,22,33),(44,55,66)])
y=np.array([(89,78,67),(22,33,45)])
print(t*y)

[[ 979 1716 2211]
 [ 968 1815 2970]]


In [18]:
t=np.array([(11,22,33),(44,55,66)])
y=np.array([(89,78,67),(22,33,45)])
print(t/y)

[[0.12359551 0.28205128 0.49253731]
 [2.         1.66666667 1.46666667]]


In [19]:
print(np.vstack((t,y)))

[[11 22 33]
 [44 55 66]
 [89 78 67]
 [22 33 45]]


In [20]:
print(np.hstack((t,y)))

[[11 22 33 89 78 67]
 [44 55 66 22 33 45]]


In [21]:
print(t.ravel())

[11 22 33 44 55 66]


In [23]:
j=np.array([[88,99,79],[55,66,77]],"float")
j

array([[88., 99., 79.],
       [55., 66., 77.]])

In [25]:
g=np.zeros((4,4))
g

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
h=np.random.random((2,2))
h

array([[0.26739297, 0.65155113],
       [0.67996899, 0.3758023 ]])

In [31]:
r=np.arange(0,40,5)
r

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [33]:
t=np.array([(111,222,333),(555,444,666)])
k=t.flatten()
print(k)

[111 222 333 555 444 666]
