In [1]:
import numpy as np


In [2]:
p=np.array([1,2,3])
print(p)

[1 2 3]


In [3]:
r=np.array([(1,2,3),(4,5,6)])
print(r)

[[1 2 3]
 [4 5 6]]


In [4]:
print(r.ndim)

2


In [5]:
print(p.ndim)

1


In [6]:
print(r.dtype)

int32


In [7]:
print(r.size)

6


In [8]:
l=np.array([(10,20,30,40,50,60,70,80),(1,2,3,4,5,6,7,8)])
print(l)

[[10 20 30 40 50 60 70 80]
 [ 1  2  3  4  5  6  7  8]]


In [9]:
print(l.shape)

(2, 8)


In [10]:
t=np.array([(10,20,30,40,50,60,70),(1,2,3,4,5,6,7,8)])
print(t.shape)

(2,)


C:\Users\ABHIJITH\AppData\Local\Temp\ipykernel_16736\3855870567.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  t=np.array([(10,20,30,40,50,60,70),(1,2,3,4,5,6,7,8)])


In [11]:
l=l.reshape(8,2)
l

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

In [12]:
l=l.reshape(4,4)
l

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [13]:
l=l.reshape(16,1)
l

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8]])

In [14]:
k=np.array([(1,2,3,4),(5,6,7,8)])
k

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
print(k[0,2])

3


In [16]:
print(k[0, :])

[1 2 3 4]


In [17]:
print(k[0])

[1 2 3 4]


In [18]:
print(k[0:,3])

[4 8]


In [19]:
a=np.array([(1,2,3),(3,4,5),(5,6,7)])
print(a[0:,2])

[3 5 7]


In [20]:
print(a[0:2,2])

[3 5]


In [21]:
w=np.linspace(1,3,5)
w

array([1. , 1.5, 2. , 2.5, 3. ])

In [22]:
q=np.linspace(1,5,10)
q

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
s=np.array([1,2,3])
print(s.max())

3


In [24]:
print(s.min())

1


In [25]:
print(s.sum())

6


In [26]:
x=np.array([(1,2,3),(9,8,7)])
print(np.sqrt(x))

[[1.         1.41421356 1.73205081]
 [3.         2.82842712 2.64575131]]


In [28]:
j=np.array([(2,3,4),(6,7,8)])
u=np.array([(1,2,3),(9,8,7)])
print(j+u)

[[ 3  5  7]
 [15 15 15]]


In [29]:
j=np.array([(2,3,4),(6,7,8)])
u=np.array([(1,2,3),(9,8,7)])
print(j-u)

[[ 1  1  1]
 [-3 -1  1]]


In [30]:
j=np.array([(2,3,4),(6,7,8)])
u=np.array([(1,2,3),(9,8,7)])
print(j*u)

[[ 2  6 12]
 [54 56 56]]


In [31]:
j=np.array([(2,3,4),(6,7,8)])
u=np.array([(1,2,3),(9,8,7)])
print(j/u)

[[2.         1.5        1.33333333]
 [0.66666667 0.875      1.14285714]]


In [32]:
print(np.vstack((j,u)))

[[2 3 4]
 [6 7 8]
 [1 2 3]
 [9 8 7]]


In [33]:
print(np.hstack((j,u)))

[[2 3 4 1 2 3]
 [6 7 8 9 8 7]]


In [34]:
print(j.ravel())

[2 3 4 6 7 8]


In [35]:
print(u.ravel())

[1 2 3 9 8 7]


In [36]:
h=np.array([[11,22,33],[55,66,77]],dtype="float")
h

array([[11., 22., 33.],
       [55., 66., 77.]])

In [37]:
r=np.zeros((3,4))
r

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
u=np.random.random((2,2))
u

array([[0.23190164, 0.70597363],
       [0.53043793, 0.67008761]])

In [44]:
b=np.arange(0,30,5)
b

array([ 0,  5, 10, 15, 20, 25])

In [49]:
k=np.array([(111,222,333),(666,777,888)])
y=k.flatten()
print(y)

[111 222 333 666 777 888]
